### ISSUE TITLE
Sorting Algorithms

### ISSUE THREAD

**Issue by swaroop-2021** [SuriyaaVijay/code-dump#236]
I want to add the following sorting algorithms,

1) Bubble Sort
2) Selection Sort
3) Insertion Sort
4) Heap Sort
5) Merge Sort
6) Quick Sort

Please Assign me this issue and add the hacktoberfest2023 tags, I am interested to Contribute : )

**Comment by Pradyumn04** [comment]
Kindly assign me this task with hacktober fest tag

**Comment by Ishika0-0** [comment]
@SuriyaaVijay Can I contribute to #236 issue I am interested in this topic

**Comment by prasad-chaudhari172** [comment]
I want to contribute to this issue. Can I contribute to #236 issue @SuriyaaVijay

**Comment by kshitijdshah99** [comment]
Hello @SuriyaaVijay I am willing to contribute to this issue pls allow me
I will add following sorting algorithms
Bubble Sort
Selection Sort
Insertion Sort
Heap Sort
Merge Sort
Quick Sort
I have made an implementation of RNNs and transformer from scratch using numpy libraries...this project will help me enhance my DSA skills

**Comment by rohitramteke1** [comment]
kindly assign me the task brother

**Comment by kshitijdshah99** [comment]
> kindly assign me the task brother

Yeah sure bro
